name: ss-server

services:
  server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:8000"
    networks:
      - server-network
    volumes:
      - ../app:/opt/app
      - ../requirements.txt:/opt/app/requirements.txt

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - server-network
    volumes:
      - db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/mydatabase
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
    volumes: 
      - ../app/auth/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - server-network
    command: start-dev --import-realm

  keycloak_init:
    build:
      context: ../
      dockerfile: docker/keycloak.Dockerfile
    networks:
      - server-network
    depends_on:
      - keycloak
    restart: on-failure
    environment:
      - PYTHONUNBUFFERED=1

networks:
  server-network:
    driver: bridge

volumes:
  db-data:
    driver: local
