name: ss-server

services:
    server:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "5000:8000"
        networks:
            - star-sync
        volumes:
            - ../app:/opt/app
            - ../requirements.txt:/opt/app/requirements.txt

networks:
    # assuming ss-deploy's db is running
    star-sync:
        driver: bridge
        name: star-sync_star-sync
        external: true

volumes:
    db-data:
        driver: local
