name: ss-server

services:
    server:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        ports:
            - "5000:5000"
        networks:
            - server-network
        develop:
            watch:
                - action: sync
                  path: ../flaskr
                  target: /app
                - action: rebuild
                  path: ../requirements.txt
                  target: /app
    # eventually, we will need to load the environment vars from a file
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydatabase
        ports:
            - "5432:5432"
        networks:
            - server-network
        volumes:
            - db-data:/var/lib/postgresql/data

networks:
    server-network:
        driver: bridge

volumes:
    db-data:
        driver: local
